### ISSUE TITLE
Create Initial Prompts

### ISSUE THREAD

**Issue by SuperDasMan** [SuperDasMan/Team-Profile-Generator#1]
**Description**

create prompts for team members and their information
create a template HTML file to be generated that displays a nicely formatted team roster based on user input

**Comment by A-BMT02** [comment]
I'll like  take a look at this 
Assign it to me

**Comment by SuperDasMan** [comment]
While I greatly appreciate your offer to assist, this is for a class
project that's meant to be done solo to gauge how well I'm learning the
material. However, I would love to work on a collab at some point in the
near future, as I'm looking to start picking up some freelance work before
completing the course.

**Comment by A-BMT02** [comment]
No problem man i understand .

It would be great to work on a collab.

Lets exchange twitter.
I'm @AhmadBMTahir on twitter.

**Comment by SuperDasMan** [comment]
Awesome! @Das_West I'm not terribly active on Twitter, but I try to keep up
on important notifications

**Comment by A-BMT02** [comment]
Followed ✅
